# Generated by Django 4.2.1 on 2023-05-21 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_Courses',
            field=models.ManyToManyField(to='students.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
    ]
