# Generated by Django 4.2.1 on 2023-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_studentcourse_exam_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='exam_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
